package com.example.tcrsuperapp.api

class ApiAdmin {
    companion object {
//        private val SERVER = "http://10.0.2.2/fuboru_tcr_superapp/admin/"
        private val SERVER = "http://tcrcorp.id/fuboru_tcr_superapp/admin/"
        val ABSENSI = SERVER + "absensi.php"
        val ABSENSI_APPROVAL = SERVER + "absensi_approval.php"
        val ABSENSI_DETAIL = SERVER + "absensi_detail.php"
        val CUSTOMER = SERVER + "customer.php"
        val FBL = SERVER + "fbl.php"
        val GALERY = SERVER + "galery.php"
        val IZIN = SERVER + "izin.php"
        val IZIN_ADD = SERVER + "izin_add.php"
        val IZIN_COUNT = SERVER + "izin_count.php"
        val IZIN_DETAIL = SERVER + "izin_detail.php"
        val IZIN_DETAIL_APPROVAL = SERVER + "izin_detail_approval.php"
        val IZIN_DETAIL_UPDATE = SERVER + "izin_detail_update.php"
        val MASUKAN_ADD = SERVER + "masukan_add.php"
        val MASUKAN_COUNT = SERVER + "masukan_count.php"
        val OMZET = SERVER + "omzet.php"
        val OMZET_TOTAL = SERVER + "omzet_total.php"
        val PENGGUNA = SERVER + "pengguna.php"
        val RETUR = SERVER + "retur.php"
        val RETUR_DETAIL = SERVER + "retur_detail.php"
        val SALES = SERVER + "sales.php"
        val SALES_ADD = SERVER + "sales_add.php"
        val SALES_COUNT = SERVER + "sales_count.php"
        val SALES_DETAIL = SERVER + "sales_detail.php"
        val SALES_SEARCH = SERVER + "sales_search.php"
        val SALES_TARGET_1 = SERVER + "sales_target_1.php"
        val SALES_TARGET_2 = SERVER + "sales_target_2.php"
        val SALES_TARGET_DETAIL = SERVER + "sales_target_detail.php"
        val SP = SERVER + "sp.php"
        val SP_DETAIL = SERVER + "sp_detail.php"
        val STOK = SERVER + "stok.php"
        val SURVEY = SERVER + "survey.php"
        val SURVEY_ADD = SERVER + "survey_add.php"
        val SURVEY_COUNT = SERVER + "survey_count.php"
        val SURVEY_DETAIL = SERVER + "survey_detail.php"
        val SURVEY_SEARCH = SERVER + "survey_search.php"
    }
}